Fix EL9 PGDG repo detection in test Dockerfiles

diff --git a/cache-config/testing/docker/traffic_ops/Dockerfile b/cache-config/testing/docker/traffic_ops/Dockerfile
--- a/cache-config/testing/docker/traffic_ops/Dockerfile
+++ b/cache-config/testing/docker/traffic_ops/Dockerfile
@@ -37,21 +37,24 @@ RUN if [[ "${OS_VERSION%%.*}" -eq 7 ]]; then \
 RUN set -o nounset -o errexit && \
 	mkdir -p /etc/cron.d; \
 	if [[ "${OS_VERSION%%.*}" -eq 7 ]]; then \
-		use_repo=''; \
 		enable_repo=''; \
 		# needed for llvm-toolset-7-clang, which is needed for postgresql13-devel-13.X-1PGDG, required by TO rpm
 		dnf -y install gcc centos-release-scl-rh; \
 	elif [[ "${OS_VERSION%%.*}" -ge 9 ]]; then \
-		use_repo='--repo=pgdg13'; \
 		enable_repo='--enablerepo=crb'; \
 	else \
-		use_repo='--repo=pgdg13'; \
 		enable_repo='--enablerepo=powertools'; \
 	fi; \
 	dnf -y install "https://download.postgresql.org/pub/repos/yum/reporpms/EL-${OS_VERSION%%.*}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"; \
 	# libicu required by postgresql13
 	dnf -y install libicu; \
-	dnf -y $use_repo -- install postgresql13; \
+	pgdg_repo="$(dnf -q repolist --all | awk '$1 ~ /^pgdg13/ {print $1; exit}')"; \
+	if [[ -z "$pgdg_repo" ]]; then \
+		echo 'ERROR: expected a pgdg13 repository after installing pgdg-redhat-repo.' >&2; \
+		dnf repolist --all >&2; \
+		exit 1; \
+	fi; \
+	dnf -y --enablerepo="$pgdg_repo" install postgresql13; \
 	dnf -y install epel-release; \
 	dnf -y $enable_repo install      \
 		bind-utils           \
diff --git a/tc-health-client/testing/docker/db_init/Dockerfile b/tc-health-client/testing/docker/db_init/Dockerfile
--- a/tc-health-client/testing/docker/db_init/Dockerfile
+++ b/tc-health-client/testing/docker/db_init/Dockerfile
@@ -26,7 +26,13 @@ RUN dnf install -y \
 	epel-release \
     libicu \
 	"https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-$(rpm --eval %_arch)/pgdg-redhat-repo-latest.noarch.rpm" && \
-    dnf -y --repo=pgdg13 install postgresql13 && \
+	pgdg_repo="$(dnf -q repolist --all | awk '$1 ~ /^pgdg13/ {print $1; exit}')" && \
+	if [[ -z "$pgdg_repo" ]]; then \
+		echo 'ERROR: expected a pgdg13 repository after installing pgdg-redhat-repo.' >&2; \
+		dnf repolist --all >&2; \
+		exit 1; \
+	fi && \
+    dnf -y --enablerepo="$pgdg_repo" install postgresql13 && \
 	dnf -y remove pgdg-redhat-repo
 
 RUN dnf -y install \
